version: "3.8"
services:
    nats:
        image: nats:latest
        ports:
            - "4222:4222"
        container_name: nats
        command: ["-js"]
        environment:
            - NATS_USER=user1
            - NATS_PASSWORD=password1

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        container_name: redis

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        container_name: mongo
